language: node_js
node_js:
    - "0.12"
    - iojs
script: npm test
env:
  - PORT=8080 BASE_URL="http://localhost:8080" STATIC_PATH="static" SESSION_SECRET="338e281187f9e8f66c792705203b4c50" REDIS_SESSION_STORE_PREFIX="example:" REDIS_URL="redis://localhost:6379/" REDIS_DATABASE=0
services:
  - redis-server
